local _, addonTable = ...
local config = addonTable.config
if not config.module.SetAddon then
    return
end


local addonFun = config.module.AddonFun
local api = config.module.API


local IsAddOnLoaded = api.IsAddOnLoaded
local GetAddOnMetadata = api.GetAddOnMetadata
local wipe = api.wipe


local font = {
    number = "Interface\\AddOns\\!7UI\\Font\\Number.ttf",
    normal = "Interface\\AddOns\\!7UI\\Font\\Normal.ttf",
    letter = "Interface\\AddOns\\!7UI\\Font\\Letter.ttf"
}


addonFun.Dominos = function(profileKeys, chars, pages1, pages2)
    if not IsAddOnLoaded("Dominos") then
        return
    end

    local addonVersion = GetAddOnMetadata("Dominos", 'Version')

    if Dominos then
        -- Hook OnProfileChanged
        function Dominos:OnProfileChanged(msg, db, name)
            self:Load()
        end

        -- 修改动作条按钮上的字体
        if Dominos.ActionButton then
            -- 快捷键
            hooksecurefunc(Dominos.ActionButton, "SetShowBindingText", function(self)
                if self.HotKey then
                    self.HotKey:SetFont(font.letter, 14, "OUTLINE")
                    self.HotKey:SetVertexColor(1, 1, 1)
                end
            end)

            -- 宏
            hooksecurefunc(Dominos.ActionButton, "SetShowMacroText", function(self)
                if self.Name then
                    self.Name:SetFont(font.normal, 12, "OUTLINE")
                    self.Name:SetVertexColor(1, 1, 1)
                end
            end)

            -- 技能充能计数
            hooksecurefunc(Dominos.ActionButton, "SetShowCounts", function(self)
                if self.Name then
                    self.Count:SetFont(font.number, 14, "OUTLINE")
                    self.Count:SetVertexColor(1, 1, 1)
                end
            end)
        end
    end

    if DominosDB then
        wipe(DominosDB)
    end

    DominosDB = {
        ["namespaces"] = {
            ["LibDualSpec-1.0"] = {},
            ["ProgressBars"] = {
                ["char"] = chars,
                ["global"] = {
                    ["version"] = 2,
                },
                ["profiles"] = {
                    ["Default"] = {
                        ["skip_inactive_modes"] = true,
                    },
                    ["监视条"] = {
                        ["skip_inactive_modes"] = true,
                    },
                },
            },
        },
        ["profileKeys"] = profileKeys,
        ["global"] = {
            ["bindingsVersion"] = 3,
            ["addonVersion"] = addonVersion,
            ["configVersion"] = 2,
        },
        ["profiles"] = {
            ["Default"] = {
                ["frames"] = {
                    { -- 动作条1
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 2,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages1,
                    },
                    { -- 动作条2
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条3
                        ["point"] = "RIGHT",
                        ["relPoint"] = "RIGHT",
                        ["x"] = -2,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["columns"] = 1,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条4
                        ["point"] = "RIGHT",
                        ["relPoint"] = "RIGHT",
                        ["x"] = -52,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["columns"] = 1,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条5
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 102,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条6
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 52,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条7
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条8
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条9
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条10
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条11
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条12
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条13
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条14
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    -- 监视进度条
                    ["exp"] = {
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["scale"] = 1,
                        ["lockMode"] = true,
                        ["padW"] = 2,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = 0,
                        ["x"] = 0,
                        ["fadeInDuration"] = 0.1,
                        ["numButtons"] = 1,
                        ["texture"] = "Blizzard Raid Bar",
                        ["display"] = {
                            ["value"] = true,
                            ["label"] = true,
                            ["max"] = true,
                            ["bonus"] = true,
                        },
                        ["hidden"] = true,
                        ["columns"] = 20,
                        ["displayLayer"] = "BACKGROUND",
                        ["padH"] = 2,
                        ["width"] = 402,
                        ["fadeOutDelay"] = false,
                        ["relPoint"] = "BOTTOM",
                        ["alwaysShowText"] = true,
                        ["font"] = "聊天",
                        ["height"] = 12,
                        ["fadeInDelay"] = false,
                        ["y"] = 36,
                        ["displayLevel"] = 1,
                    },
                    -- 姿态条
                    ["class"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOMLEFT",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOPLEFT",
                            ["y"] = 0,
                            ["x"] = -1,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 839,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["padW"] = 2,
                        ["spacing"] = 3,
                        ["padH"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 宠物条
                    ["pet"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOP",
                            ["y"] = 0,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["spacing"] = 3,
                        ["padH"] = 2,
                        ["padW"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 附身条
                    ["possess"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOMRIGHT",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOPRIGHT",
                            ["y"] = 0,
                            ["x"] = 1,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOMRIGHT",
                        ["relPoint"] = "BOTTOMRIGHT",
                        ["x"] = -839,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["padW"] = 2,
                        ["spacing"] = 4,
                        ["padH"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 施法条
                    ["cast"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = 5,
                            ["y"] = 40,
                            ["x"] = 0,
                        },
                        ["useSpellReactionColors"] = true,
                        ["scale"] = 1,
                        ["latencyPadding"] = 400,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["texture"] = "Blizzard Raid Bar",
                        ["showInPetBattleUI"] = true,
                        ["displayLayer"] = "HIGH",
                        ["showInOverrideUI"] = true,
                        ["w"] = 220,
                        ["h"] = 24,
                        ["padH"] = 2,
                        ["fadeOutDelay"] = false,
                        ["font"] = "聊天",
                        ["padW"] = 2,
                        ["display"] = {
                            ["time"] = true,
                            ["spark"] = true,
                            ["icon"] = true,
                            ["border"] = true,
                            ["latency"] = true,
                        },
                        ["fadeInDelay"] = false,
                        ["hidden"] = true,
                        ["showstates"] = "",
                    },
                    -- 战斗条
                    ["encounter"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = 5,
                            ["y"] = 80,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["scale"] = 1,
                        ["showInOverrideUI"] = true,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["fadeInDelay"] = false,
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                    },
                    -- 额外技能
                    ["extra"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "encounter",
                            ["y"] = 10,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["showInOverrideUI"] = true,
                        ["displayLayer"] = "HIGH",
                    },
                    -- Roll
                    ["roll"] = {
                        ["showInPetBattleUI"] = true,
                        ["columns"] = 1,
                        ["scale"] = 1,
                        ["showInOverrideUI"] = true,
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "encounter",
                            ["y"] = 10,
                            ["x"] = 0,
                        },
                        ["spacing"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 警报
                    ["alerts"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "roll",
                            ["y"] = 2,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["columns"] = 1,
                        ["showInOverrideUI"] = true,
                        ["spacing"] = 2,
                    },
                    -- 菜单
                    ["menu"] = {
                        ["fadeOutDelay"] = false,
                        ["point"] = "TOPLEFT",
                        ["relPoint"] = "TOPLEFT",
                        ["showstates"] = "",
                        ["scale"] = 0.8,
                        ["fadeInDuration"] = 0.1,
                        ["y"] = 0,
                        ["x"] = 0,
                        ["fadeAlpha"] = 0.4,
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = -4,
                        ["rowOffset"] = 0,
                        ["fadeInDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                    },
                    -- 背包
                    ["bags"] = {
                        ["scale"] = 1,
                        ["keyRing"] = false,
                        ["rowOffset"] = 0,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = 2,
                        ["anchor"] = {
                            ["relFrame"] = "menu",
                            ["point"] = "TOPLEFT",
                            ["relPoint"] = "TOPRIGHT",
                            ["y"] = 0,
                            ["x"] = 0,
                        },
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["showInPetBattleUI"] = false,
                        ["showInOverrideUI"] = false,
                        ["hidden"] = true,
                        ["fadeInDelay"] = false,
                        ["fadeOutDelay"] = false,
                        ["oneBag"] = true,
                    },
                    -- 时间1
                    ["mirrorTimer1"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -96,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 时间2
                    ["mirrorTimer2"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -122,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 时间3
                    ["mirrorTimer3"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -148,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 对话特写头像
                    ["talk"] = {
                        ["anchor"] = {
                            ["relFrame"] = "mirrorTimer3",
                            ["point"] = "TOP",
                            ["relPoint"] = "BOTTOM",
                            ["y"] = -10,
                            ["x"] = 0,
                        },
                        ["hidden"] = true,
                        ["showInPetBattleUI"] = true,
                        ["showInOverrideUI"] = true,
                        ["displayLayer"] = "LOW",
                    },
                    -- 地下城查找器
                    ["queue"] = {
                        ["x"] = -294,
                        ["y"] = -294,
                        ["scale"] = 0.68,
                        ["point"] = "CENTER",
                        ["relPoint"] = "TOPRIGHT",
                        ["displayLayer"] = "MEDIUM",
                    },
                },
                ["showCounts"] = true,
                ["minimap"] = {
                    ["hide"] = true,
                },
                ["ab"] = {
                    ["rightClickUnit"] = "none",
                },
                ["useOverrideUI"] = false,
                ["showEmptyButtons"] = true,
                ["showSpellAnimations"] = false,
                ["linkedOpacity"] = true,
            },
            ["监视条"] = {
                ["frames"] = {
                    { -- 动作条1
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 2,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages1,
                    },
                    { -- 动作条2
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条3
                        ["point"] = "RIGHT",
                        ["relPoint"] = "RIGHT",
                        ["x"] = -2,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["columns"] = 1,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条4
                        ["point"] = "RIGHT",
                        ["relPoint"] = "RIGHT",
                        ["x"] = -52,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["columns"] = 1,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条5
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 128,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条6
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 78,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条7
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条8
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条9
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条10
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条11
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条12
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条13
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    { -- 动作条14
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 0,
                        ["y"] = 0,
                        ["scale"] = 0.68,
                        ["unit"] = "none",
                        ["rightClickUnit"] = "none",
                        ["padW"] = 2,
                        ["padH"] = 2,
                        ["spacing"] = 5,
                        ["rowOffset"] = 0,
                        ["rowSpacing"] = 0,
                        ["numButtons"] = 12,
                        ["hidden"] = true,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["pages"] = pages2,
                    },
                    -- 监视进度条
                    ["exp"] = {
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["scale"] = 1,
                        ["lockMode"] = true,
                        ["padW"] = 2,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = 0,
                        ["x"] = 0,
                        ["fadeInDuration"] = 0.1,
                        ["numButtons"] = 1,
                        ["texture"] = "Blizzard Raid Bar",
                        ["display"] = {
                            ["value"] = true,
                            ["label"] = true,
                            ["max"] = true,
                            ["bonus"] = true,
                        },
                        ["columns"] = 20,
                        ["displayLayer"] = "BACKGROUND",
                        ["padH"] = 2,
                        ["width"] = 402,
                        ["fadeOutDelay"] = false,
                        ["relPoint"] = "BOTTOM",
                        ["alwaysShowText"] = true,
                        ["font"] = "聊天",
                        ["height"] = 12,
                        ["fadeInDelay"] = false,
                        ["y"] = 36,
                        ["displayLevel"] = 1,
                    },
                    -- 姿态条
                    ["class"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOMLEFT",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOPLEFT",
                            ["y"] = 0,
                            ["x"] = -1,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOMLEFT",
                        ["relPoint"] = "BOTTOMLEFT",
                        ["x"] = 839,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["padW"] = 2,
                        ["spacing"] = 3,
                        ["padH"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 宠物条
                    ["pet"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOP",
                            ["y"] = 0,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOM",
                        ["relPoint"] = "BOTTOM",
                        ["x"] = 0,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["spacing"] = 3,
                        ["padH"] = 2,
                        ["padW"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 附身条
                    ["possess"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOMRIGHT",
                            ["relFrame"] = 5,
                            ["relPoint"] = "TOPRIGHT",
                            ["y"] = 0,
                            ["x"] = 1,
                        },
                        ["showInPetBattleUI"] = false,
                        ["point"] = "BOTTOMRIGHT",
                        ["relPoint"] = "BOTTOMRIGHT",
                        ["x"] = -839,
                        ["y"] = 114,
                        ["scale"] = 0.9,
                        ["showInOverrideUI"] = false,
                        ["padW"] = 2,
                        ["spacing"] = 4,
                        ["padH"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 施法条
                    ["cast"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = 5,
                            ["y"] = 40,
                            ["x"] = 0,
                        },
                        ["useSpellReactionColors"] = true,
                        ["scale"] = 1,
                        ["latencyPadding"] = 400,
                        ["fadeOutDuration"] = 0.1,
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["texture"] = "Blizzard Raid Bar",
                        ["showInPetBattleUI"] = true,
                        ["displayLayer"] = "HIGH",
                        ["showInOverrideUI"] = true,
                        ["w"] = 220,
                        ["h"] = 24,
                        ["padH"] = 2,
                        ["fadeOutDelay"] = false,
                        ["font"] = "聊天",
                        ["padW"] = 2,
                        ["display"] = {
                            ["time"] = true,
                            ["spark"] = true,
                            ["icon"] = true,
                            ["border"] = true,
                            ["latency"] = true,
                        },
                        ["fadeInDelay"] = false,
                        ["hidden"] = true,
                        ["showstates"] = "",
                    },
                    -- 战斗条
                    ["encounter"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = 5,
                            ["y"] = 80,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["scale"] = 1,
                        ["showInOverrideUI"] = true,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["fadeOutDelay"] = false,
                        ["fadeInDelay"] = false,
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                    },
                    -- 额外技能
                    ["extra"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "encounter",
                            ["y"] = 10,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["showInOverrideUI"] = true,
                        ["displayLayer"] = "HIGH",
                    },
                    -- Roll
                    ["roll"] = {
                        ["showInPetBattleUI"] = true,
                        ["columns"] = 1,
                        ["scale"] = 1,
                        ["showInOverrideUI"] = true,
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "encounter",
                            ["y"] = 10,
                            ["x"] = 0,
                        },
                        ["spacing"] = 2,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "MEDIUM",
                    },
                    -- 警报
                    ["alerts"] = {
                        ["anchor"] = {
                            ["point"] = "BOTTOM",
                            ["relPoint"] = "TOP",
                            ["relFrame"] = "roll",
                            ["y"] = 2,
                            ["x"] = 0,
                        },
                        ["showInPetBattleUI"] = true,
                        ["columns"] = 1,
                        ["showInOverrideUI"] = true,
                        ["spacing"] = 2,
                    },
                    -- 菜单
                    ["menu"] = {
                        ["fadeOutDelay"] = false,
                        ["point"] = "TOPLEFT",
                        ["relPoint"] = "TOPLEFT",
                        ["showstates"] = "",
                        ["scale"] = 0.8,
                        ["fadeInDuration"] = 0.1,
                        ["y"] = 0,
                        ["x"] = 0,
                        ["fadeAlpha"] = 0.4,
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = -4,
                        ["rowOffset"] = 0,
                        ["fadeInDelay"] = false,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                    },
                    -- 背包
                    ["bags"] = {
                        ["scale"] = 1,
                        ["keyRing"] = false,
                        ["rowOffset"] = 0,
                        ["showstates"] = "",
                        ["fadeOutDuration"] = 0.1,
                        ["spacing"] = 2,
                        ["anchor"] = {
                            ["relFrame"] = "menu",
                            ["point"] = "TOPLEFT",
                            ["relPoint"] = "TOPRIGHT",
                            ["y"] = 0,
                            ["x"] = 0,
                        },
                        ["fadeInDuration"] = 0.1,
                        ["displayLevel"] = 1,
                        ["displayLayer"] = "LOW",
                        ["showInPetBattleUI"] = false,
                        ["showInOverrideUI"] = false,
                        ["hidden"] = true,
                        ["fadeInDelay"] = false,
                        ["fadeOutDelay"] = false,
                        ["oneBag"] = true,
                    },
                    -- 时间1
                    ["mirrorTimer1"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -96,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 时间2
                    ["mirrorTimer2"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -122,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 时间3
                    ["mirrorTimer3"] = {
                        ["point"] = "TOP",
                        ["w"] = 206,
                        ["texture"] = "Blizzard Raid Bar",
                        ["y"] = -148,
                        ["x"] = 0,
                        ["h"] = 26,
                        ["font"] = "默认",
                        ["display"] = {
                            ["border"] = true,
                            ["time"] = false,
                            ["spark"] = false,
                            ["label"] = true,
                        },
                        ["padH"] = 1,
                        ["padW"] = 1,
                        ["displayLayer"] = "HIGH",
                    },
                    -- 对话特写头像
                    ["talk"] = {
                        ["anchor"] = {
                            ["relFrame"] = "mirrorTimer3",
                            ["point"] = "TOP",
                            ["relPoint"] = "BOTTOM",
                            ["y"] = -10,
                            ["x"] = 0,
                        },
                        ["hidden"] = true,
                        ["showInPetBattleUI"] = true,
                        ["showInOverrideUI"] = true,
                        ["displayLayer"] = "LOW",
                    },
                    -- 地下城查找器
                    ["queue"] = {
                        ["x"] = -294,
                        ["y"] = -294,
                        ["scale"] = 0.68,
                        ["point"] = "CENTER",
                        ["relPoint"] = "TOPRIGHT",
                        ["displayLayer"] = "MEDIUM",
                    },
                },
                ["showCounts"] = true,
                ["minimap"] = {
                    ["hide"] = true,
                },
                ["ab"] = {
                    ["rightClickUnit"] = "none",
                },
                ["useOverrideUI"] = false,
                ["showEmptyButtons"] = true,
                ["showSpellAnimations"] = false,
                ["linkedOpacity"] = true,
            },
        }
    }
end
